apiVersion: v1
kind: Service
metadata:
  name: wave-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: wave-demo
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

